# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\ge_Tools\src\developer\main\uvtools\widget\ui\moveuvUI.ui'
#
# Created: Sun Oct 12 09:14:56 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(461, 188)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnUpLeft = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpLeft.sizePolicy().hasHeightForWidth())
        self.btnUpLeft.setSizePolicy(sizePolicy)
        self.btnUpLeft.setBaseSize(QtCore.QSize(6, 0))
        self.btnUpLeft.setStyleSheet(_fromUtf8(""))
        self.btnUpLeft.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_10.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpLeft.setIcon(icon)
        self.btnUpLeft.setIconSize(QtCore.QSize(32, 32))
        self.btnUpLeft.setFlat(True)
        self.btnUpLeft.setObjectName(_fromUtf8("btnUpLeft"))
        self.gridLayout.addWidget(self.btnUpLeft, 0, 0, 1, 1)
        self.btnUp = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUp.sizePolicy().hasHeightForWidth())
        self.btnUp.setSizePolicy(sizePolicy)
        self.btnUp.setStyleSheet(_fromUtf8(""))
        self.btnUp.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUp.setIcon(icon1)
        self.btnUp.setIconSize(QtCore.QSize(32, 32))
        self.btnUp.setFlat(True)
        self.btnUp.setObjectName(_fromUtf8("btnUp"))
        self.gridLayout.addWidget(self.btnUp, 0, 1, 1, 1)
        self.btnUpRight = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpRight.sizePolicy().hasHeightForWidth())
        self.btnUpRight.setSizePolicy(sizePolicy)
        self.btnUpRight.setStyleSheet(_fromUtf8(""))
        self.btnUpRight.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpRight.setIcon(icon2)
        self.btnUpRight.setIconSize(QtCore.QSize(32, 32))
        self.btnUpRight.setFlat(True)
        self.btnUpRight.setObjectName(_fromUtf8("btnUpRight"))
        self.gridLayout.addWidget(self.btnUpRight, 0, 2, 1, 1)
        self.btnLeft = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLeft.sizePolicy().hasHeightForWidth())
        self.btnLeft.setSizePolicy(sizePolicy)
        self.btnLeft.setStyleSheet(_fromUtf8(""))
        self.btnLeft.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_9.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLeft.setIcon(icon3)
        self.btnLeft.setIconSize(QtCore.QSize(32, 32))
        self.btnLeft.setFlat(True)
        self.btnLeft.setObjectName(_fromUtf8("btnLeft"))
        self.gridLayout.addWidget(self.btnLeft, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit.setStyleSheet(_fromUtf8("QLineEdit {\n"
"padding: 4px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 10px;\n"
"font:  bold 11px\n"
"}"))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.btnRight = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRight.sizePolicy().hasHeightForWidth())
        self.btnRight.setSizePolicy(sizePolicy)
        self.btnRight.setStyleSheet(_fromUtf8(""))
        self.btnRight.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_U.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRight.setIcon(icon4)
        self.btnRight.setIconSize(QtCore.QSize(32, 32))
        self.btnRight.setFlat(True)
        self.btnRight.setObjectName(_fromUtf8("btnRight"))
        self.gridLayout.addWidget(self.btnRight, 1, 2, 1, 1)
        self.btnDownLeft = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownLeft.sizePolicy().hasHeightForWidth())
        self.btnDownLeft.setSizePolicy(sizePolicy)
        self.btnDownLeft.setStyleSheet(_fromUtf8(""))
        self.btnDownLeft.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_8.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownLeft.setIcon(icon5)
        self.btnDownLeft.setIconSize(QtCore.QSize(32, 32))
        self.btnDownLeft.setAutoRepeat(False)
        self.btnDownLeft.setAutoExclusive(False)
        self.btnDownLeft.setAutoRepeatDelay(0)
        self.btnDownLeft.setAutoRepeatInterval(0)
        self.btnDownLeft.setFlat(True)
        self.btnDownLeft.setObjectName(_fromUtf8("btnDownLeft"))
        self.gridLayout.addWidget(self.btnDownLeft, 2, 0, 1, 1)
        self.btnDown = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDown.sizePolicy().hasHeightForWidth())
        self.btnDown.setSizePolicy(sizePolicy)
        self.btnDown.setStyleSheet(_fromUtf8(""))
        self.btnDown.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDown.setIcon(icon6)
        self.btnDown.setIconSize(QtCore.QSize(32, 32))
        self.btnDown.setFlat(True)
        self.btnDown.setObjectName(_fromUtf8("btnDown"))
        self.gridLayout.addWidget(self.btnDown, 2, 1, 1, 1)
        self.btnDownRight = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownRight.sizePolicy().hasHeightForWidth())
        self.btnDownRight.setSizePolicy(sizePolicy)
        self.btnDownRight.setStyleSheet(_fromUtf8(""))
        self.btnDownRight.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow_4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownRight.setIcon(icon7)
        self.btnDownRight.setIconSize(QtCore.QSize(32, 32))
        self.btnDownRight.setCheckable(False)
        self.btnDownRight.setAutoDefault(False)
        self.btnDownRight.setDefault(False)
        self.btnDownRight.setFlat(True)
        self.btnDownRight.setObjectName(_fromUtf8("btnDownRight"))
        self.gridLayout.addWidget(self.btnDownRight, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnMirrorU = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorU.sizePolicy().hasHeightForWidth())
        self.btnMirrorU.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnMirrorU.setFont(font)
        self.btnMirrorU.setObjectName(_fromUtf8("btnMirrorU"))
        self.horizontalLayout_3.addWidget(self.btnMirrorU)
        self.btnMirrorV = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorV.sizePolicy().hasHeightForWidth())
        self.btnMirrorV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnMirrorV.setFont(font)
        self.btnMirrorV.setObjectName(_fromUtf8("btnMirrorV"))
        self.horizontalLayout_3.addWidget(self.btnMirrorV)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "type number", None))
        self.btnMirrorU.setText(_translate("MainWindow", "Mirror U", None))
        self.btnMirrorV.setText(_translate("MainWindow", "Mirror V", None))

import developer.main.source.IconResource_rc
