# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\maya_Tools\src\developer\main\assetContent\ui\AssetContentUI.ui'
#
# Created: Thu Sep 18 14:38:24 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1387, 781)
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowOpacity(0.0)
        MainWindow.setStyleSheet(_fromUtf8("background-image: url(:/Project/window_bg.png);"))
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ldtFilter_2 = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldtFilter_2.sizePolicy().hasHeightForWidth())
        self.ldtFilter_2.setSizePolicy(sizePolicy)
        self.ldtFilter_2.setObjectName(_fromUtf8("ldtFilter_2"))
        self.horizontalLayout_2.addWidget(self.ldtFilter_2)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.treeViewPath = QtGui.QTreeView(self.layoutWidget)
        self.treeViewPath.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeViewPath.sizePolicy().hasHeightForWidth())
        self.treeViewPath.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.472224, 1.0, 0.468, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(34, 34, 34))
        gradient.setColorAt(1.0, QtGui.QColor(102, 102, 102))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.treeViewPath.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.treeViewPath.setFont(font)
        self.treeViewPath.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeViewPath.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:0.472224, y1:1, x2:0.468, y2:0, stop:0 rgba(34, 34, 34, 255), stop:1 rgba(102, 102, 102, 255));\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.treeViewPath.setLineWidth(9)
        self.treeViewPath.setMidLineWidth(16)
        self.treeViewPath.setAutoScrollMargin(21)
        self.treeViewPath.setDragEnabled(True)
        self.treeViewPath.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeViewPath.setAlternatingRowColors(False)
        self.treeViewPath.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeViewPath.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeViewPath.setIconSize(QtCore.QSize(20, 20))
        self.treeViewPath.setUniformRowHeights(True)
        self.treeViewPath.setItemsExpandable(True)
        self.treeViewPath.setAnimated(True)
        self.treeViewPath.setWordWrap(True)
        self.treeViewPath.setHeaderHidden(True)
        self.treeViewPath.setObjectName(_fromUtf8("treeViewPath"))
        self.treeViewPath.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeViewPath)
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnSearch = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        self.btnSearch.setMouseTracking(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/arrow-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearch.setIcon(icon1)
        self.btnSearch.setFlat(True)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.horizontalLayout.addWidget(self.btnSearch)
        self.ldtFilter = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldtFilter.sizePolicy().hasHeightForWidth())
        self.ldtFilter.setSizePolicy(sizePolicy)
        self.ldtFilter.setObjectName(_fromUtf8("ldtFilter"))
        self.horizontalLayout.addWidget(self.ldtFilter)
        self.horizontalSlider = QtGui.QSlider(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:0.472224, y1:1, x2:0.468, y2:0, stop:0 rgba(34, 34, 34, 255), stop:1 rgba(102, 102, 102, 255));\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.verticalLayout_4.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet(_fromUtf8(""))
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.txtFileInfo = QtGui.QTextBrowser(self.tab_3)
        self.txtFileInfo.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.523, y1:0.119, x2:0.523, y2:0.87, stop:0 rgba(66, 96, 122, 255), stop:1 rgba(3, 65, 99, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.txtFileInfo.setObjectName(_fromUtf8("txtFileInfo"))
        self.verticalLayout_5.addWidget(self.txtFileInfo)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter_3 = QtGui.QSplitter(self.tab_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.tableQAResult = QtGui.QTableView(self.splitter_3)
        self.tableQAResult.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.523, y1:0.119, x2:0.523, y2:0.87, stop:0 rgba(66, 96, 122, 255), stop:1 rgba(3, 65, 99, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.tableQAResult.setAlternatingRowColors(True)
        self.tableQAResult.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableQAResult.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableQAResult.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableQAResult.setGridStyle(QtCore.Qt.SolidLine)
        self.tableQAResult.setSortingEnabled(True)
        self.tableQAResult.setObjectName(_fromUtf8("tableQAResult"))
        self.tableQAResult.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.splitter_3)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.tab_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.formLayoutWidget = QtGui.QWidget(self.splitter_2)
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.splitter_2)
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter_4 = QtGui.QSplitter(self.tab_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.splitter_4)
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_6.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.splitter_4)
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.listWidget = QtGui.QListWidget(self.formLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.523, y1:0.119, x2:0.523, y2:0.87, stop:0 rgba(66, 96, 122, 255), stop:1 rgba(3, 65, 99, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.SpanningRole, self.listWidget)
        self.verticalLayout_8.addWidget(self.splitter_4)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.splitter_6 = QtGui.QSplitter(self.tab_7)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.splitter_5 = QtGui.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_5)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.cbbProjectName = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbbProjectName.sizePolicy().hasHeightForWidth())
        self.cbbProjectName.setSizePolicy(sizePolicy)
        self.cbbProjectName.setMinimumContentsLength(20)
        self.cbbProjectName.setObjectName(_fromUtf8("cbbProjectName"))
        self.verticalLayout_15.addWidget(self.cbbProjectName)
        spacerItem = QtGui.QSpacerItem(144, 321, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.tabWidget_3 = QtGui.QTabWidget(self.splitter_5)
        self.tabWidget_3.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_3.setDocumentMode(True)
        self.tabWidget_3.setMovable(True)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.tab_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.tab_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.comboBox_4 = QtGui.QComboBox(self.tab_8)
        self.comboBox_4.setMinimumContentsLength(10)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_5.addWidget(self.comboBox_4)
        self.label_9 = QtGui.QLabel(self.tab_8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.comboBox_5 = QtGui.QComboBox(self.tab_8)
        self.comboBox_5.setMinimumContentsLength(10)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.label_10 = QtGui.QLabel(self.tab_8)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.comboBox_6 = QtGui.QComboBox(self.tab_8)
        self.comboBox_6.setMinimumContentsLength(10)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.horizontalLayout_5.addWidget(self.comboBox_6)
        self.label_12 = QtGui.QLabel(self.tab_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.cbbIssueStatus = QtGui.QComboBox(self.tab_8)
        self.cbbIssueStatus.setObjectName(_fromUtf8("cbbIssueStatus"))
        self.horizontalLayout_5.addWidget(self.cbbIssueStatus)
        self.line_5 = QtGui.QFrame(self.tab_8)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_5.addWidget(self.line_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.line = QtGui.QFrame(self.tab_8)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.pushButton_11 = QtGui.QPushButton(self.tab_8)
        self.pushButton_11.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.tab_8)
        self.pushButton_12.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_3 = QtGui.QPushButton(self.tab_8)
        self.pushButton_3.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/Edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_13 = QtGui.QPushButton(self.tab_8)
        self.pushButton_13.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Project/Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon5)
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_5.addWidget(self.pushButton_13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.listWidgetIssue = QtGui.QListWidget(self.tab_8)
        self.listWidgetIssue.setAlternatingRowColors(True)
        self.listWidgetIssue.setObjectName(_fromUtf8("listWidgetIssue"))
        self.verticalLayout_11.addWidget(self.listWidgetIssue)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.tab_9)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.label_6 = QtGui.QLabel(self.tab_9)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_8 = QtGui.QComboBox(self.tab_9)
        self.comboBox_8.setMinimumContentsLength(10)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.horizontalLayout_6.addWidget(self.comboBox_8)
        self.label_13 = QtGui.QLabel(self.tab_9)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.cbbTaskStatus = QtGui.QComboBox(self.tab_9)
        self.cbbTaskStatus.setObjectName(_fromUtf8("cbbTaskStatus"))
        self.horizontalLayout_6.addWidget(self.cbbTaskStatus)
        self.line_4 = QtGui.QFrame(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_6.addWidget(self.line_4)
        self.label = QtGui.QLabel(self.tab_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.radioButton = QtGui.QRadioButton(self.tab_9)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.tab_9)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.tab_9)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.treeView_2 = QtGui.QTreeView(self.tab_9)
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.verticalLayout_12.addWidget(self.treeView_2)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.Asset = QtGui.QWidget()
        self.Asset.setObjectName(_fromUtf8("Asset"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.Asset)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.Asset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_2 = QtGui.QPushButton(self.Asset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.line_3 = QtGui.QFrame(self.Asset)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_3.addWidget(self.line_3)
        self.label_3 = QtGui.QLabel(self.Asset)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.Asset)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbbGroup = QtGui.QComboBox(self.Asset)
        self.cbbGroup.setEditable(True)
        self.cbbGroup.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.cbbGroup.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbbGroup.setMinimumContentsLength(5)
        self.cbbGroup.setObjectName(_fromUtf8("cbbGroup"))
        self.horizontalLayout_3.addWidget(self.cbbGroup)
        self.label_4 = QtGui.QLabel(self.Asset)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_2 = QtGui.QComboBox(self.Asset)
        self.comboBox_2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_2.setMinimumContentsLength(5)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.label_5 = QtGui.QLabel(self.Asset)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cbbAssetStatus = QtGui.QComboBox(self.Asset)
        self.cbbAssetStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbbAssetStatus.setObjectName(_fromUtf8("cbbAssetStatus"))
        self.horizontalLayout_3.addWidget(self.cbbAssetStatus)
        self.line_2 = QtGui.QFrame(self.Asset)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.listWidgetAsset = QtGui.QListWidget(self.Asset)
        self.listWidgetAsset.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.523, y1:0.119, x2:0.523, y2:0.87, stop:0 rgba(66, 96, 122, 255), stop:1 rgba(3, 65, 99, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.listWidgetAsset.setAutoScrollMargin(5)
        self.listWidgetAsset.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidgetAsset.setDragEnabled(True)
        self.listWidgetAsset.setAlternatingRowColors(True)
        self.listWidgetAsset.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.listWidgetAsset.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidgetAsset.setIconSize(QtCore.QSize(75, 75))
        self.listWidgetAsset.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidgetAsset.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidgetAsset.setResizeMode(QtGui.QListView.Adjust)
        self.listWidgetAsset.setGridSize(QtCore.QSize(75, 90))
        self.listWidgetAsset.setViewMode(QtGui.QListView.IconMode)
        self.listWidgetAsset.setModelColumn(0)
        self.listWidgetAsset.setUniformItemSizes(True)
        self.listWidgetAsset.setWordWrap(True)
        self.listWidgetAsset.setObjectName(_fromUtf8("listWidgetAsset"))
        self.verticalLayout_10.addWidget(self.listWidgetAsset)
        self.tabWidget_3.addTab(self.Asset, _fromUtf8(""))
        self.tabWidget_4 = QtGui.QTabWidget(self.splitter_6)
        self.tabWidget_4.setMovable(True)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_10)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.pushButton_5 = QtGui.QPushButton(self.tab_10)
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_10 = QtGui.QPushButton(self.tab_10)
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_4 = QtGui.QPushButton(self.tab_10)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_6 = QtGui.QPushButton(self.tab_10)
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.listView = QtGui.QListView(self.tab_10)
        self.listView.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.523, y1:0.119, x2:0.523, y2:0.87, stop:0 rgba(66, 96, 122, 255), stop:1 rgba(3, 65, 99, 255));\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/images/strip.png);"))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout_13.addWidget(self.listView)
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_11)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton_8 = QtGui.QPushButton(self.tab_11)
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.tab_11)
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.pushButton_7 = QtGui.QPushButton(self.tab_11)
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.treeView_3 = QtGui.QTreeView(self.tab_11)
        self.treeView_3.setObjectName(_fromUtf8("treeView_3"))
        self.verticalLayout_14.addWidget(self.treeView_3)
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.splitter_6)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        self.menuConnect_with_Source_Control = QtGui.QMenu(self.menuPreferences)
        self.menuConnect_with_Source_Control.setObjectName(_fromUtf8("menuConnect_with_Source_Control"))
        self.menuHelps = QtGui.QMenu(self.menubar)
        self.menuHelps.setObjectName(_fromUtf8("menuHelps"))
        self.menuProjects = QtGui.QMenu(self.menubar)
        self.menuProjects.setObjectName(_fromUtf8("menuProjects"))
        self.menuViews = QtGui.QMenu(self.menubar)
        self.menuViews.setObjectName(_fromUtf8("menuViews"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuSend_to = QtGui.QMenu(self.menuEdit)
        self.menuSend_to.setObjectName(_fromUtf8("menuSend_to"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionPerforce = QtGui.QAction(MainWindow)
        self.actionPerforce.setObjectName(_fromUtf8("actionPerforce"))
        self.actionSVN = QtGui.QAction(MainWindow)
        self.actionSVN.setObjectName(_fromUtf8("actionSVN"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpen_selected_asset = QtGui.QAction(MainWindow)
        self.actionOpen_selected_asset.setObjectName(_fromUtf8("actionOpen_selected_asset"))
        self.actionMax = QtGui.QAction(MainWindow)
        self.actionMax.setObjectName(_fromUtf8("actionMax"))
        self.actionCapture_thumbnail = QtGui.QAction(MainWindow)
        self.actionCapture_thumbnail.setObjectName(_fromUtf8("actionCapture_thumbnail"))
        self.actionImport_selected_asset = QtGui.QAction(MainWindow)
        self.actionImport_selected_asset.setObjectName(_fromUtf8("actionImport_selected_asset"))
        self.actionChange_Color_theme = QtGui.QAction(MainWindow)
        self.actionChange_Color_theme.setObjectName(_fromUtf8("actionChange_Color_theme"))
        self.actionSign_out = QtGui.QAction(MainWindow)
        self.actionSign_out.setObjectName(_fromUtf8("actionSign_out"))
        self.menuConnect_with_Source_Control.addAction(self.actionPerforce)
        self.menuConnect_with_Source_Control.addAction(self.actionSVN)
        self.menuPreferences.addAction(self.menuConnect_with_Source_Control.menuAction())
        self.menuPreferences.addAction(self.actionChange_Color_theme)
        self.menuHelps.addAction(self.actionAbout)
        self.menuProjects.addAction(self.actionOpen)
        self.menuProjects.addAction(self.actionSign_out)
        self.menuSend_to.addAction(self.actionMax)
        self.menuEdit.addAction(self.actionOpen_selected_asset)
        self.menuEdit.addAction(self.menuSend_to.menuAction())
        self.menuEdit.addAction(self.actionCapture_thumbnail)
        self.menuEdit.addAction(self.actionImport_selected_asset)
        self.menubar.addAction(self.menuProjects.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuHelps.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Asset Content", None))
        self.btnSearch.setText(_translate("MainWindow", "Filter Asset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Asset Browser", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Scene Information", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Geometry", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Textures", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Shaders", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Asset QA", None))
        self.label_7.setText(_translate("MainWindow", "Filtered:", None))
        self.label_8.setText(_translate("MainWindow", "by Leader", None))
        self.label_9.setText(_translate("MainWindow", "by Artist", None))
        self.label_10.setText(_translate("MainWindow", "by Priority", None))
        self.label_12.setText(_translate("MainWindow", "by Status", None))
        self.pushButton_11.setToolTip(_translate("MainWindow", "Create new issue", None))
        self.pushButton_12.setToolTip(_translate("MainWindow", "Issue solved", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "edit issue", None))
        self.pushButton_13.setToolTip(_translate("MainWindow", "remove issue", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Issue Tracking", None))
        self.label_11.setText(_translate("MainWindow", "Filtered:", None))
        self.label_6.setText(_translate("MainWindow", "Artist", None))
        self.label_13.setText(_translate("MainWindow", "Status", None))
        self.label.setText(_translate("MainWindow", "Request", None))
        self.radioButton.setText(_translate("MainWindow", "to Art", None))
        self.radioButton_2.setText(_translate("MainWindow", "to Tech", None))
        self.radioButton_3.setText(_translate("MainWindow", "to Client", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Tasks", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "--Type Asset Name", None))
        self.pushButton_2.setText(_translate("MainWindow", "Search", None))
        self.label_3.setText(_translate("MainWindow", "Filtered:", None))
        self.label_2.setText(_translate("MainWindow", "Group", None))
        self.label_4.setText(_translate("MainWindow", "Artist", None))
        self.label_5.setText(_translate("MainWindow", "Status", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Asset), _translate("MainWindow", "Asset Tracking", None))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Create new issue", None))
        self.pushButton_10.setToolTip(_translate("MainWindow", "Issue solved", None))
        self.pushButton_4.setToolTip(_translate("MainWindow", "edit issue", None))
        self.pushButton_6.setToolTip(_translate("MainWindow", "remove issue", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Issue", None))
        self.pushButton_7.setToolTip(_translate("MainWindow", "edit Task", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Tasks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Asset Tracking", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences", None))
        self.menuConnect_with_Source_Control.setTitle(_translate("MainWindow", "Connect with Source Control", None))
        self.menuHelps.setTitle(_translate("MainWindow", "Helps", None))
        self.menuProjects.setTitle(_translate("MainWindow", "Projects", None))
        self.menuViews.setTitle(_translate("MainWindow", "Views", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Asset", None))
        self.menuSend_to.setTitle(_translate("MainWindow", "Export selected asset", None))
        self.actionPerforce.setText(_translate("MainWindow", "Perforce", None))
        self.actionSVN.setText(_translate("MainWindow", "SVN", None))
        self.actionOpen.setText(_translate("MainWindow", "Sign in", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOpen_selected_asset.setText(_translate("MainWindow", "Open selected asset", None))
        self.actionMax.setText(_translate("MainWindow", "Max", None))
        self.actionCapture_thumbnail.setText(_translate("MainWindow", "Capture thumbnail...", None))
        self.actionImport_selected_asset.setText(_translate("MainWindow", "Import selected asset", None))
        self.actionChange_Color_theme.setText(_translate("MainWindow", "Change Color Theme", None))
        self.actionSign_out.setText(_translate("MainWindow", "Sign out", None))

import developer.main.source.IconResource_rc
