# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\maya_Tools\src\developer\main\polytools\mirrortools\ui\mirrorUI.ui'
#
# Created: Tue Jun 24 12:43:16 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(329, 224)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rdbNoClone = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdbNoClone.setFont(font)
        self.rdbNoClone.setChecked(False)
        self.rdbNoClone.setObjectName(_fromUtf8("rdbNoClone"))
        self.horizontalLayout_8.addWidget(self.rdbNoClone)
        self.rdbClone = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdbClone.setFont(font)
        self.rdbClone.setChecked(True)
        self.rdbClone.setObjectName(_fromUtf8("rdbClone"))
        self.horizontalLayout_8.addWidget(self.rdbClone)
        self.rdbInstance = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdbInstance.setFont(font)
        self.rdbInstance.setObjectName(_fromUtf8("rdbInstance"))
        self.horizontalLayout_8.addWidget(self.rdbInstance)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.rdbKeepHistory = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdbKeepHistory.setFont(font)
        self.rdbKeepHistory.setChecked(False)
        self.rdbKeepHistory.setObjectName(_fromUtf8("rdbKeepHistory"))
        self.horizontalLayout_17.addWidget(self.rdbKeepHistory)
        self.rdbParentOnly = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdbParentOnly.setFont(font)
        self.rdbParentOnly.setObjectName(_fromUtf8("rdbParentOnly"))
        self.horizontalLayout_17.addWidget(self.rdbParentOnly)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btnMirrorU = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorU.sizePolicy().hasHeightForWidth())
        self.btnMirrorU.setSizePolicy(sizePolicy)
        self.btnMirrorU.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.btnMirrorU.setCheckable(True)
        self.btnMirrorU.setObjectName(_fromUtf8("btnMirrorU"))
        self.horizontalLayout_9.addWidget(self.btnMirrorU)
        self.btnAxisX = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisX.sizePolicy().hasHeightForWidth())
        self.btnAxisX.setSizePolicy(sizePolicy)
        self.btnAxisX.setObjectName(_fromUtf8("btnAxisX"))
        self.horizontalLayout_9.addWidget(self.btnAxisX)
        self.btnPivotX = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPivotX.sizePolicy().hasHeightForWidth())
        self.btnPivotX.setSizePolicy(sizePolicy)
        self.btnPivotX.setObjectName(_fromUtf8("btnPivotX"))
        self.horizontalLayout_9.addWidget(self.btnPivotX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_10.addWidget(self.pushButton_7)
        self.btnAxisY = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisY.sizePolicy().hasHeightForWidth())
        self.btnAxisY.setSizePolicy(sizePolicy)
        self.btnAxisY.setObjectName(_fromUtf8("btnAxisY"))
        self.horizontalLayout_10.addWidget(self.btnAxisY)
        self.btnPivotY = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPivotY.sizePolicy().hasHeightForWidth())
        self.btnPivotY.setSizePolicy(sizePolicy)
        self.btnPivotY.setObjectName(_fromUtf8("btnPivotY"))
        self.horizontalLayout_10.addWidget(self.btnPivotY)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.btnMirrorV = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorV.sizePolicy().hasHeightForWidth())
        self.btnMirrorV.setSizePolicy(sizePolicy)
        self.btnMirrorV.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);"))
        self.btnMirrorV.setCheckable(True)
        self.btnMirrorV.setObjectName(_fromUtf8("btnMirrorV"))
        self.horizontalLayout_11.addWidget(self.btnMirrorV)
        self.btnAxisZ = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisZ.sizePolicy().hasHeightForWidth())
        self.btnAxisZ.setSizePolicy(sizePolicy)
        self.btnAxisZ.setObjectName(_fromUtf8("btnAxisZ"))
        self.horizontalLayout_11.addWidget(self.btnAxisZ)
        self.btnPivotZ = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPivotZ.sizePolicy().hasHeightForWidth())
        self.btnPivotZ.setSizePolicy(sizePolicy)
        self.btnPivotZ.setObjectName(_fromUtf8("btnPivotZ"))
        self.horizontalLayout_11.addWidget(self.btnPivotZ)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_2.setTitle(_translate("Form", "Mirror Toolbox", None))
        self.rdbNoClone.setText(_translate("Form", "No Copy", None))
        self.rdbClone.setText(_translate("Form", "Clone", None))
        self.rdbInstance.setText(_translate("Form", "Instance", None))
        self.rdbKeepHistory.setToolTip(_translate("Form", "Mirror selected mesh with history intact", None))
        self.rdbKeepHistory.setText(_translate("Form", "Keep History", None))
        self.rdbParentOnly.setText(_translate("Form", "Parent Only", None))
        self.btnMirrorU.setText(_translate("Form", "X", None))
        self.btnAxisX.setToolTip(_translate("Form", "Mirror selected mesh by axis", None))
        self.btnAxisX.setText(_translate("Form", "By Axis", None))
        self.btnPivotX.setToolTip(_translate("Form", "Mirror selected mesh by pivot", None))
        self.btnPivotX.setText(_translate("Form", "By Pivot", None))
        self.pushButton_7.setText(_translate("Form", "Y", None))
        self.btnAxisY.setToolTip(_translate("Form", "Mirror selected mesh by pivot", None))
        self.btnAxisY.setText(_translate("Form", "By Axis", None))
        self.btnPivotY.setToolTip(_translate("Form", "Mirror selected mesh by axis", None))
        self.btnPivotY.setText(_translate("Form", "By Pivot", None))
        self.btnMirrorV.setText(_translate("Form", "Z", None))
        self.btnAxisZ.setToolTip(_translate("Form", "Mirror selected mesh by axis", None))
        self.btnAxisZ.setText(_translate("Form", "By Axis", None))
        self.btnPivotZ.setToolTip(_translate("Form", "Mirror selected mesh by pivot", None))
        self.btnPivotZ.setText(_translate("Form", "By Pivot", None))

